### ISSUE TITLE
Other functions in Jobs should have optional parameters

### ISSUE THREAD

**Issue by pdincau** [pdincau/ex_jenkins#14]
The functions with multiple parameters `stop/2`, `log/2` and `status/2` in Jobs module should be refactored as it was the `start/2` function.

**Comment by pdincau** [comment]
fixed in 55725b4a69c2a6f0a8d63ef299abdca9f4d1f37d

**Comment by chazsconi** [comment]
@pdincau Can you create a new release of the package plaese as I would like to use it?  If you want, and you think I have permission, I can also do it.

**Comment by pdincau** [comment]
With this issue? The last one in hex.pm should already have it.

**Comment by pdincau** [comment]
@chazsconi i invited you as collaborator but it seems you have not accepted yet

**Comment by chazsconi** [comment]
@pdincau I accepted the invite now, but you need to add me as an owner to the project in hex.pm to be able to publish.  You can use the `mix hex.owner` to do this.

**Comment by chazsconi** [comment]
@pdincau You can find me on the elixir slack channel (chazsconi) if you want to discuss
