### ISSUE TITLE
Port ex_jenkins on hex.pm

### ISSUE THREAD

**Issue by pdincau** [pdincau/ex_jenkins#4]
As suggested by @chazsconi ex_jenkins will be ported to hex.pm

**Comment by pdincau** [comment]
@chazsconi I would like to add you as a maintainer. What do you think?

**Comment by chazsconi** [comment]
@pdincau Yes, quite happy to be added as a maintainer.

**Comment by pdincau** [comment]
Closed in 2e73ba2..c7e3d77
