### ISSUE TITLE
Some API methods have an optional last parameter making them difficult to extend

### ISSUE THREAD

**Issue by chazsconi** [pdincau/ex_jenkins#5]
Hi @pdincau 

In creating the last PR (for parameterized jobs) it would have been nicer to just extend the existing `Jobs.start` function (currently it is like this)
```elixir
def start(job, token \\ ExJenkins.token) do
    post("job/" <> job <> "/build?token=" <> token, "")
    |> handle_start_job_response
end
```
to add the Jenkins build parameters as an additional argument, however this was not possible as the last argument is optional.

Can I suggest that the signature of functions are changed to pass optional arguments as options instead?

Although this is a breaking change, it would allow the functions to be extended more easily without further breaking changes.

So the `Jobs.start` function would become:

```elixir
def start(job, opts \\ []) do
    token = Keyword.get(opts, :token, ExJenkins.token)
    post("job/" <> job <> "/build?token=" <> token, "")
    |> handle_start_job_response
end
```
This would then be invoked as
```elixir
start("my-job", token: "my-token")
```

This would allow another option to be passed `:build_parameters` without having to have a separate `build_with_parameters` function.

I would like to enhance the `Jobs.status` function to respond with additional information if an additional option is passed (the parameters used for a parameterized build), but I cannot do this without creating a new function at the moment.

Thanks

Charles

**Comment by pdincau** [comment]
@chazsconi seems ok to me. At the moment we have no stable version, so I am not worried about breaking changes. Would you like to be assigned with this issue?

**Comment by chazsconi** [comment]
Yes - I will try to fix this when I have time.

**Comment by pdincau** [comment]
@chazsconi if you want I can take a look at this one since I have some free time this week.

**Comment by chazsconi** [comment]
@pdincau Yes, sure.  I can check the PR when you are done.

**Comment by chazsconi** [comment]
@pdincau I'm not sure if this should be closed because the `status`, `log` and `stop` functions also currently have an optional last parameter for the build number.  This should also probably be passed as a keyword list e.g. `status("my-job", number: 123)`

**Comment by pdincau** [comment]
@chazsconi let me open a different issue for that 👍

**Comment by pdincau** [comment]
closed https://github.com/pdincau/ex_jenkins/issues/14
